from typing import Protocol, Optional, Any, Dict, List

class UserRepositoryPort(Protocol):
    def get_by_email(self, s, email: str) -> Optional[Dict[str, Any]]: ...
    def get_active_by_email(self, s, email: str) -> Optional[Dict[str, Any]]: ...
    def get_by_id(self, s, user_id: str) -> Optional[Dict[str, Any]]: ...
    def list_users(self, s, *, limit: int = 50, offset: int = 0) -> List[Dict[str, Any]]: ...
    def create_user(self, s, *, email: str, password_hash: str, nombre: Optional[str], telefono: Optional[str]) -> str: ...
    def touch_last_login(self, s, user_id: str) -> None: ...
    def update_user_fields(self, s, user_id: str, changes: Dict[str, Any]) -> int: ...
    def soft_delete(self, s, user_id: str) -> int: ...

class RoleReaderPort(Protocol):
    def get_role_code_for_user(self, s, user_id: str) -> Optional[str]: ...
    def set_single_role_for_user(self, s, user_id: str, role_code: str) -> None: ...
