apiVersion: v1
kind: Secret
metadata:
  name: admin-service-token
  namespace: eventos-peru
type: Opaque
data:
  token: ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnBjM01pT2lKemRYQnlaV1F1WTI5dElpd2ljM1ZpSWpvaVlXUnRhVzR4SW4wLmFkbWluLXRva2VuLXRlc3Q=  # "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.admin-token-test" en base64