apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: default
data:
  # URLs de los microservicios internos en Kubernetes
  VITE_IAM_URL: "http://iam-service.default.svc.cluster.local:8010"
  VITE_CATALOGO_URL: "http://catalogo-service.default.svc.cluster.local:8020"
  VITE_PROVEEDORES_URL: "http://proveedores-service.default.svc.cluster.local:8030"
  VITE_CONTRATACION_URL: "http://contratacion-service.default.svc.cluster.local:8040"
