apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eventos-api
  namespace: eventos-peru
  annotations:
    kubernetes.io/ingress.class: public
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, PUT, POST, DELETE, PATCH, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Authorization, Content-Type, Accept, Origin, X-Requested-With"
    nginx.ingress.kubernetes.io/limit-rps: "20"
    # Solo HTTP por ahora: sin redirección a HTTPS
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-hide-headers: "Strict-Transport-Security"
spec:
  ingressClassName: public
  rules:
    - host: eventos.emeday.inc
      http:
        paths:
          # 🔹 Rutas que usará el FRONTEND
          #    /api/iam/**  → iam-service:8010
          #    /api/catalogo/** → catalogo-service:8020
          #    /api/proveedores/** → proveedores-service:8030
          #    /api/contratacion/** → contratacion-service:8040

          - path: /api/iam
            pathType: Prefix
            backend:
              service:
                name: iam-service
                port:
                  number: 8010

          - path: /api/catalogo
            pathType: Prefix
            backend:
              service:
                name: catalogo-service
                port:
                  number: 8020

          - path: /api/proveedores
            pathType: Prefix
            backend:
              service:
                name: proveedores-service
                port:
                  number: 8030

          - path: /api/contratacion
            pathType: Prefix
            backend:
              service:
                name: contratacion-service
                port:
                  number: 8040

          # 🔹 Acceso directo a cada servicio (útil para docs / Swagger en laboratorio)
          - path: /iam
            pathType: Prefix
            backend:
              service:
                name: iam-service
                port:
                  number: 8010

          - path: /catalogo
            pathType: Prefix
            backend:
              service:
                name: catalogo-service
                port:
                  number: 8020

          - path: /proveedores
            pathType: Prefix
            backend:
              service:
                name: proveedores-service
                port:
                  number: 8030

          - path: /contratacion
            pathType: Prefix
            backend:
              service:
                name: contratacion-service
                port:
                  number: 8040
