"""
Check pedido detail in DB and propose fixes.
Usage:
  python tools/check_pedido_db.py --pedido <pedido_id> [--host HOST --port PORT --user USER --pass PASS]

Defaults (from repo bootstrap):
  user=app_contratacion
  password=Contrata_2025
  host=127.0.0.1
  port=3306

The script will:
 - Connect to MySQL using PyMySQL
 - Query `ev_contratacion.pedido_evento`, `ev_contratacion.item_pedido_evento`, `ev_contratacion.reserva`
 - Optionally query read views `ev_contratacion.v_pedido_con_cliente` and `ev_contratacion.v_reserva_detalle`
 - Analyze missing prices, mismatched subtotals, missing items/reservas and suggest SQL updates
 - Write a suggested SQL patch to `db/seed_demo_pedido_fix.sql` (not applied automatically)

Install dependencies:
  pip install pymysql

Author: Generated by assistant
"""
import os
import argparse
import decimal
import json
from typing import Any

try:
    import pymysql
except Exception as e:
    raise RuntimeError('This script requires pymysql. Install with: pip install pymysql')

# Default connection values (from db/bootstrap.sql)
DEFAULTS = {
    'host': os.environ.get('DB_HOST', '127.0.0.1'),
    'port': int(os.environ.get('DB_PORT', 3306)),
    'user': os.environ.get('DB_USER', 'app_contratacion'),
    'password': os.environ.get('DB_PASS', 'Contrata_2025'),
}

# Tolerance for subtotal check
EPS = decimal.Decimal('0.05')

STATE_MAP = {
    0: 'DRAFT',
    1: 'COTIZADO',
    2: 'APROBADO',
    3: 'ASIGNADO',
    4: 'CERRADO',
    5: 'CANCELADO'
}

SQL_FIX_PATH = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'db', 'seed_demo_pedido_fix.sql')


def connect(cfg: dict):
    return pymysql.connect(host=cfg['host'], port=cfg['port'], user=cfg['user'],
                           password=cfg['password'], cursorclass=pymysql.cursors.DictCursor,
                           autocommit=True)


def fetch_one(conn, sql: str, params: dict = None):
    with conn.cursor() as cur:
        cur.execute(sql, params or {})
        return cur.fetchone()


def fetch_all(conn, sql: str, params: dict = None):
    with conn.cursor() as cur:
        cur.execute(sql, params or {})
        return cur.fetchall()


def map_state(n):
    try:
        return STATE_MAP[int(n)]
    except Exception:
        return str(n)


def analyze(pedido_id: str, conn) -> dict:
    report = {'pedido': None, 'items': [], 'reservas': [], 'issues': [], 'suggested_sql': []}

    # 1) pedido
    pedido_sql = """
    SELECT * FROM ev_contratacion.pedido_evento WHERE id = %s LIMIT 1
    """
    pedido = fetch_one(conn, pedido_sql, (pedido_id,))
    if not pedido:
        report['issues'].append(f'Pedido {pedido_id} no encontrado')
        return report
    report['pedido'] = pedido

    # 2) items
    items_sql = """
    SELECT id, pedido_id, opcion_servicio_id, nombre_servicio, cantidad, precio_unitario, subtotal, tipo_item, referencia_id, precio_unit, precio_total
    FROM ev_contratacion.item_pedido_evento
    WHERE pedido_id = %s
    ORDER BY created_at
    """
    items = fetch_all(conn, items_sql, (pedido_id,))
    report['items'] = items

    # 3) reservas
    reservas_sql = """
    SELECT r.id, r.item_pedido_id, r.proveedor_id, r.inicio, r.fin, r.status, r.hold_id, r.created_at
    FROM ev_contratacion.reserva r
    JOIN ev_contratacion.item_pedido_evento i ON i.id = r.item_pedido_id
    WHERE i.pedido_id = %s
    ORDER BY r.created_at
    """
    reservas = fetch_all(conn, reservas_sql, (pedido_id,))
    report['reservas'] = reservas

    # Analysis: items existence
    if len(items) == 0:
        report['issues'].append('El pedido no tiene items registrados')
    else:
        # Check item price/subtotal
        for it in items:
            # determine precio_unit
            precio_unit = None
            if it.get('precio_unitario') is not None:
                precio_unit = decimal.Decimal(str(it['precio_unitario']))
            elif it.get('precio_unit') is not None:
                precio_unit = decimal.Decimal(str(it['precio_unit']))
            elif it.get('precio_total') is not None and it.get('cantidad'):
                precio_unit = decimal.Decimal(str(it['precio_total'])) / decimal.Decimal(str(it['cantidad']))

            cantidad = decimal.Decimal(str(it.get('cantidad') or 1))
            subtotal = None
            if it.get('subtotal') is not None:
                subtotal = decimal.Decimal(str(it['subtotal']))
            elif it.get('precio_total') is not None:
                subtotal = decimal.Decimal(str(it['precio_total']))

            # detect missing price
            if precio_unit is None or precio_unit == 0:
                report['issues'].append(f"Item {it['id']} sin precio unitario definido")
                # Suggest using catalog price if available via opcion_servicio_id, else fallback
                report['suggested_sql'].append(f"-- TODO: set precio_unitario for item {it['id']}")

            # check subtotal consistency
            if subtotal is not None and precio_unit is not None:
                expected = (precio_unit * cantidad).quantize(decimal.Decimal('0.01'))
                if abs(subtotal - expected) > EPS:
                    report['issues'].append(f"Item {it['id']} subtotal inconsistent: {subtotal} != {precio_unit}*{cantidad} = {expected}")
                    # Suggest UPDATE
                    upd = (
                        "UPDATE ev_contratacion.item_pedido_evento\n"
                        f"SET precio_unitario = {precio_unit}, subtotal = {expected}, precio_unit = {precio_unit}, precio_total = {expected}\n"
                        f"WHERE id = '{it['id']}';"
                    )
                    report['suggested_sql'].append(upd)

    # Check reservas mapping
    if len(reservas) == 0:
        report['issues'].append('No hay reservas para este pedido (esto puede ser normal si no se asignó proveedor)')
    else:
        # Check provider existence
        for r in reservas:
            prov_sql = "SELECT id, nombre, email FROM ev_proveedores.proveedor WHERE id = %s LIMIT 1"
            prov = fetch_one(conn, prov_sql, (r['proveedor_id'],))
            if not prov:
                report['issues'].append(f"Reserva {r['id']} referencia proveedor {r['proveedor_id']} no existe en ev_proveedores.proveedor")
                report['suggested_sql'].append(f"-- Verify proveedor {r['proveedor_id']} exists or update reserva {r['id']}")

    # Check pedido monto_total vs sum(items.subtotal)
    try:
        monto = decimal.Decimal(str(pedido.get('monto_total') or 0))
    except Exception:
        monto = decimal.Decimal('0')

    sum_items = decimal.Decimal('0')
    for it in items:
        s = it.get('subtotal') or it.get('precio_total') or 0
        sum_items += decimal.Decimal(str(s or 0))

    if sum_items != monto:
        report['issues'].append(f"Pedido.monto_total ({monto}) != suma items ({sum_items})")
        # suggest update
        report['suggested_sql'].append(
            f"UPDATE ev_contratacion.pedido_evento SET monto_total = {sum_items} WHERE id = '{pedido_id}';"
        )

    return report


def write_suggested_sql(suggested: list):
    if not suggested:
        print('\nNo hay SQL sugerido para aplicar.')
        return
    out_dir = os.path.dirname(SQL_FIX_PATH)
    os.makedirs(out_dir, exist_ok=True)
    with open(SQL_FIX_PATH, 'w', encoding='utf-8') as f:
        f.write('-- SQL patch generated by tools/check_pedido_db.py\n')
        f.write('-- Review before applying. Run in your DB shell as appropriate.\n\n')
        for stmt in suggested:
            f.write(stmt.strip() + '\n\n')
    print(f"\nWrote suggested SQL to: {SQL_FIX_PATH}")


def main():
    p = argparse.ArgumentParser()
    p.add_argument('--pedido', '-p', required=True, help='Pedido id (UUID)')
    p.add_argument('--host', default=DEFAULTS['host'])
    p.add_argument('--port', default=DEFAULTS['port'], type=int)
    p.add_argument('--user', default=DEFAULTS['user'])
    p.add_argument('--pass', dest='password', default=DEFAULTS['password'])
    args = p.parse_args()

    cfg = {'host': args.host, 'port': args.port, 'user': args.user, 'password': args.password}
    print('Connecting to DB with:', cfg['host'], cfg['port'], cfg['user'])

    conn = connect(cfg)
    try:
        report = analyze(args.pedido, conn)
    finally:
        conn.close()

    # Print summary
    print('\n--- Analysis Report ---')
    if report['pedido']:
        ped = report['pedido']
        print(f"Pedido {ped['id']} found. cliente_id={ped['cliente_id']}, tipo_evento_id={ped.get('tipo_evento_id')}, status={ped.get('status')} ({map_state(ped.get('status'))}), monto_total={ped.get('monto_total')}")
    else:
        print('Pedido not found')

    print(f"Items: {len(report['items'])}, Reservas: {len(report['reservas'])}")

    if report['issues']:
        print('\nIssues found:')
        for it in report['issues']:
            print(' -', it)
    else:
        print('\nNo issues detected')

    if report['suggested_sql']:
        print('\nSuggested SQL statements:')
        for s in report['suggested_sql']:
            print('---')
            print(s)

    # Save suggested SQL to file for easier apply
    write_suggested_sql(report['suggested_sql'])


if __name__ == '__main__':
    main()
